---
- name: install common packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mc

- name: add the group 'sh3d'
  group:
    name: sh3d
    state: present

- name: add the user 'sh3d'
  user:
    name: sh3d
    comment: SH3D
    group: sh3d
    shell: /bin/bash